// <auto-generated />
using ACME.Services.DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ACME.Services.DAL.Migrations
{
    [DbContext(typeof(InvestorContext))]
    [Migration("20190619131642_addition")]
    partial class addition
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ACME.Services.DAL.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode");

                    b.Property<string>("CountryName");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new { CountryId = 1, CountryCode = "AU", CountryName = "Australia" },
                        new { CountryId = 2, CountryCode = "NZ", CountryName = "New Zealand" },
                        new { CountryId = 3, CountryCode = "AQ", CountryName = "Antarctica" },
                        new { CountryId = 4, CountryCode = "AR", CountryName = "Argentina" },
                        new { CountryId = 5, CountryCode = "BR", CountryName = "Brazil" }
                    );
                });

            modelBuilder.Entity("ACME.Services.DAL.Models.Post", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BSPName");

                    b.Property<string>("Category");

                    b.Property<string>("Comments");

                    b.Property<string>("DeliveryOffice");

                    b.Property<string>("Locality");

                    b.Property<string>("ParcelZone");

                    b.Property<string>("Pcode");

                    b.Property<string>("PreSortIndicator");

                    b.Property<string>("State");

                    b.HasKey("ID");

                    b.ToTable("Posts");

                    b.HasData(
                        new { ID = 50, Category = "DeliveryArea", Locality = "ACACIA HILLS", Pcode = "0822", State = "NT" },
                        new { ID = 55, Category = "DeliveryArea", Locality = "ACTON", Pcode = "2601", State = "ACT" },
                        new { ID = 60, Category = "DeliveryArea", Locality = "AARONS PASS", Pcode = "2850", State = "NSW" },
                        new { ID = 65, Category = "DeliveryArea", Locality = "ABBEYARD", Pcode = "3737", State = "VIC" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
